stages:
  prepare_data:
    cmd: Rscript prepare_data.R
    deps:
    - prepare_data.R
    - data/train.csv
    outs: 
    - outputs/train_fold.rds
    - outputs/validation_fold.rds
  train_model:
    cmd: Rscript train_model.R
    deps:
    - train_model.R
    - outputs/train_fold.rds
    - outputs/validation_fold.rds
    outs:
    - outputs/model.rds
    metrics:
    - accuracy.txt